from batchgenerators.utilities.file_and_folder_operations import *

def load_plans_file(plans_file):
    """
    This is what actually configures the entire experiment. The plans file is generated by experiment planning
    Loads pkl or json format plan file
    convert keys in json to integer if applicable
    author: Puyang Wang
    :input:
    plans_file String
    :return:
    plans Dataframe
    """
    def convert_keys_to_int(d: dict):
        new_dict = {}
        for k, v in d.items():
            try:
                new_key = int(k)
            except ValueError:
                new_key = k
            if type(v) == dict:
                v = convert_keys_to_int(v)
            new_dict[new_key] = v
        return new_dict

    format = plans_file.split('.')[-1]
    if format == 'pkl':
        plans = load_pickle(plans_file)
    elif format == 'json':
        with open(plans_file, 'r') as f:
            plans = convert_keys_to_int(json.load(f))
    else:
        raise RuntimeError('Loading plan file format {} not supported!'.format(format))
    return plans